name: E2E on Chrome

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Create gmail_token.json from secret
        run: echo "$GMAIL_TOKEN" > cypress/fixtures/gmail_token.json
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests on Chrome
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome