name: E2E on Chrome, Firefox, and Electron

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron]

    name: E2E on ${{ matrix.browser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Create gmail_token.json from secret
        run: echo "$GMAIL_TOKEN" > cypress/fixtures/gmail_token.json
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}

      - name: Create credentials.json from secret
        run: echo "$CREDENTIALS_JSON" > cypress/fixtures/credentials.json
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
    
      - name: Create userCredentials.json from secret
        run: echo "$USER_CREDENTIALS_JSON" > cypress/fixtures/userCredentials.json
        env:
          USER_CREDENTIALS_JSON: ${{ secrets.USER_CREDENTIALS_JSON }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: ${{ matrix.browser }}